spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb?options=-c%20TimeZone%3DAsia%2FKolkata
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata

server:
  port: 8080